openapi: 3.0.3
info:
  title: Load Flow Service API
  description: An API that interacts with Powsybl
  version: 1.0.0
servers:
- url: /
paths:
  /default-values/{parameter-set}:
    get:
      description: Get default parameters for the calculations
      parameters:
      - in: path
        name: parameter-set
        schema:
          type: string
        required: true
        description: Name of the parameter set (load-flow-params, sensitivity-analysis-params, security-analysis-params)
      responses:
        200:
          description: Default load parameters as JSON
          content:
            application/json:
              type: object
        404:
          description: Returned when parameter set is not found. Possible parameter sets is listed
          content:
            plain/text:
              type: string

  /object-names/{object-type}:
    post:
      description: Extracts names for the given object
      parameters:
      - in: path
        name: object-type
        required: true
        schema:
          type: string
        description: Name of the object type for which names should be extracted (substations, voltage-levels, generators, loads, branches, buses)
      requestBody:
        $ref: '#/components/networkFile'
      responses:
        200:
          description: List with names of the specified object type
          content:
            application/json:
              type: object
        404:
          description: Object type is not known
          content:
            text/plain:
              type: string
        422:
          $ref: '#/components/missingNetworkFileResponse'
        500:
          $ref: '#/components/internalError'


  /run-load-flow:
    post:
      description: Run load flow calculation
      requestBody:
        $ref: '#/components/networkFile'


      responses:
        200:
          description: Result of load flow calculation
          content:
            application/json:
              type: object
        422:
          $ref: '#/components/missingNetworkFileResponse'
        500:
          $ref: '#/components/internalError'

  /diagram:
    post:
      description: Create a network area diagram
      requestBody:
        $ref: '#/components/networkFile'
      responses:
        200:
          $ref: '#/components/svgDiagram'
        422:
          $ref: '#/components/missingNetworkFileResponse'
        500:
          $ref: '#/components/internalError'

  /diagram/{type}/{name}:
    post:
      description: Create a diagram of a named group of components
      parameters:
      - in: path
        name: type
        description: Diagram type (generic, substation, voltage-level)
        schema:
          type: string
      - in: path
        name: name
        description: Name of the component for which a diagram should be drawn
        schema:
          type: string
      requestBody:
        $ref: '#/components/networkFile'
      responses:
        200:
          $ref: '#components/svgDiagram'
        400:
          description: Unknown type or name
          content:
            text/plain:
              type: string
        422:
          $ref: '#/components/missingNetworkFileResponse'
        500:
          $ref: '#/components/internalError'

  /sensitivity-analysis:
    post:
      description: Run a sensitivity analysis. See https://www.powsybl.org/pages/documentation/simulation/sensitivity/
      requestBody:
        $ref: '#/components/networkFile'

      responses:
        200:
          description: Result of the sensitivity analysis
          content:
            application/json:
              type: object
        422:
          $ref: '#/components/missingNetworkFileResponse'
        500:
          $ref: '#/components/internalError'

  /status/{id}:
    get:
      description: Run status for a run
      parameters:
      - in: path
        name: id
        required: true
        description: ID provided for the run (obtained from the response of the request starting the run)

      responses:
        200:
          description: Status info for the run
          content:
            application/json:
              type: object
        404:
          description: Task not found
          content:
            text/plain:
              type: string

  /result/{id}:
    get:
      description: Result for the run
      parameters:
      - in: path
        name: id
        required: true
        description: ID provided for the run (obtained from the response of the request starting the run)

      responses:
        200:
          description: Result from the run
          content:
            application/json:
              type: object
        404:
          description: Task not found
          content:
            text/plain:
              type: string

components:
  schemas:
    Bus:
      type: object
      properties:
        id:
          type: string
        voltage:
          type: double
        angle:
          type: double
        activePower:
          type: double
        reactivePower:
          type: double
    sensitivity-factor:
      type: object
      properties:
        functionType:
          type: string
        functionId:
          type: string
        variableType:
          type: string
        variableId:
          type: string
        variableSet:
          type: bool
        contingencyContextType:
          type: string
  networkFile:
    description: Form with network data sent as file
    content:
      multipart/form-data:
        schema:
          type: object
          properties:
            network:
              type: string
              format: binary
            load-flow-params:
              type: object
              description: Parameters for load flow calculations. Has effect for /run-load-flow and /sensitivity-analysis). See default-values/load-flow-params for possible fields
            sensitivity-analysis-params:
              type: object
              description: Parameters for sensitivity analysis. Has effect for /sensitivity-analysis. See /default-values/sensitivity-analysis-parameters for possible fields
            sensitivity-factors:
              type: array
              description: Sensitivity factors. Has effect for /sensitivity-analysis
              items:
                $ref: '#/components/schemas/sensitivity-factor'
            contingencies:
              type: array
              description: Contingencies. Has effect for /sensitivity-analysis
              items:
                type: object
          required:
          - network
  missingNetworkFileResponse:
    description: No network file provided
    content:
      text/plain:
        type: string

  internalError:
    description: An internal error occurred
    content:
      text/plain:
        type: string

  svgDiagram:
    description: Generated svg figure
    content:
      image/svg+xml:
        type: string
