name: Build docker image

on:
  release:
    types: [published]

jobs:
  runs-on: ubuntu-latest
  build-image:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Dockerize
      run: docker build -f ./Dockerfile -t load-flow-service:${{ github.event.release.tag_name }}

    - name: Publish
      run: echo "No publishing action implemented"