name: Build docker image

on:
  release:
    types: [published]

permissions:
  contents: read
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-image-and-publish:
    name: Publish Docker Image to Docker Hub
    runs-on: ubuntu-latest
    if: github.repository_owner == 'statnett'
    permissions:
      contents: read # for actions/checkout to fetch code
      packages: write # for docker/build-push-action to push images
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: temurin
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Docker login
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Meta data extraction
      uses: docker/metadata-action@v5
      id: meta
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    - name: Push image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
